### ISSUE TITLE
Recipe check interval control missing in new version - intentional change?

### ISSUE THREAD

**Issue by XNFu233233233** [alec016/modular-machinery-reborn#54]
First paste a new and old version configuration file

old:
```toml
	[general.General]
		#Defines the _default_ color for machine casings as items or blocks. (Hex color with alpha at start) Has to be defined both server and clientside!
		general_casing_color = "#FFFF4900"
		#Defines the _default_ color for EMI/JEI chance text color. (Hex color without alpha) Has to be defined both server and clientside!
		chance_color = "#FFFFFF"
		#Defines the time in ticks that the machine should check for a structure update.
		#20 ticks = 1 second. Default: 5
		# Default: 5
		# Range: > 1
		check_structure_ticks = 5
		#Defines the time in ticks that the machine should check for a recipe update.
		#20 ticks = 1 second. Default: 80
		# Default: 20
		# Range: > 1
		check_recipe_ticks = 20
```

new:
```toml
	[general.General]
		#Defines the _default_ color for machine casings as items or blocks. (Hex color with alpha at start) Has to be defined both server and clientside!
		general_casing_color = "#FFFF4900"
		#Defines the _default_ color for EMI/JEI chance text color. (Hex color without alpha) Has to be defined both server and clientside!
		chance_color = "#FFFFFF"
		#Defines the time in ticks that the machine should check for a structure update.
		#20 ticks = 1 second. Default: 5
		# Default: 5
		# Range: > 1
		check_structure_ticks = 5
		#Defines the number of max parallel recipes that can be run on multiblocks. Default: 256
		# Default: 256
		# Range: > 1
		check_recipe_ticks = 256
```

In the new version, check_recipe_ticks is used to set the maximum number of parallel recipes, whereas in the old version it controlled the recipe check interval.
I need to adjust the recipe check time, but the new version's config file seems to lack any other parameters related to this functionality.
Is this an oversight in development, a deliberate removal of the feature, or has it been replaced by an alternative mechanism?
